export const ADDRESS_SUCCESSFUL = 'ADDRESS_SUCCESSFUL';
export const ADDRESS_UNSUCCESSFUL = 'ADDRESS_UNSUCCESSFUL';
export const DELETE_ADDRESS_UNSUCCESSFUL = 'DELETE_ADDRESS_UNSUCCESSFUL';
export const DELETE_ADDRESS_SUCCESSFUL = 'DELETE_ADDRESS_SUCCESSFUL';
export const GET_ADDRESS_SUCCESSFUL = 'GET_ADDRESS_SUCCESSFUL';
export const GET_ADDRESS_UNSUCCESSFUL = 'GET_ADDRESS_UNSUCCESSFUL';
export const ADDRESS_LOADING = 'ADDRESS_ERROR';

export const LOADER = 'LOADER';

export const AUTH = {
  LOGIN_FAIL: 'LOGIN_FAIL',

  REGISTER_FAIL: 'REGISTER_FAIL',

  USER_LOGOUT: 'USER_LOGOUT',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  SET_USER: 'SET_USER',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  ACTIVATE_USER_SUCCESS: 'ACTIVATE_USER_SUCCESS',

  RESET_PREFIX: 'reset',
  LOGIN_PREFIX: 'login',
  FORGOT_PREFIX: 'forgot',
  REGISTER_PREFIX: 'register',
  RESEND_CODE_PREFIX: 'resend',
  VERIFY_EMAIL_PREFIX: 'verifyEmail',
};

export const APP = {
  LOADER: 'APP_LOADER',
  NAVIGATION: 'APP_NAVIGATION',
  FORCE_UPDATE: 'FORCE_UPDATE',
  SETTINGS_LOADER: 'SETTINGS_LOADER',
  FETCH_SETTINGS: 'FETCH_SETTINGS',
  FETCH_SETTINGS_PREFIX: 'settings',
  INTERNET_CONNECTION: 'INTERNET_CONNECTION',
};
export const USER = {
  GET_PROFILE: 'GET_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  UPDATE_PHONE_NUMBER: 'UPDATE_PHONE_NUMBER',
  PROFILE_ERROR: 'PROFILE_ERROR',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
  UPDATE_PHONE_NUMBER_ERROR: 'UPDATE_PHONE_NUMBER_ERROR',

  GET_PROFILE_PREFIX: 'userProfile',
  UPDATE_PROFILE_PREFIX: 'updateProfile',

  CHANGE_PASSWORD_PREFIX: 'changePassowrd',
  UPDATE_PHONE_NUMBER_PREFIX: 'updatephonenumber',
  DELETE_PHONE_NUMBER_PREFIX: 'deletephonenumber',
};
